run:
  timeout: 2m

linters-settings:
  golint:
    min-confidence: 0.1
  goimports:
    local-prefixes: github.com/dexidp/dex

linters:
  disable-all: true
  enable:
  - bodyclose
  - deadcode
  - depguard
  - dogsled
  - gochecknoinits
  - gofmt
  - goimports
  - golint
  - gosimple
  - gocritic
  - govet
  - ineffassign
  - interfacer
  - misspell
  - nakedret
  - staticcheck
  - structcheck
  - stylecheck
  - typecheck
  - unconvert
  - unused
  - varcheck
  - whitespace

  # TODO: fix linter errors before enabling
  # - unparam
  # - scopelint
  # - gosec
  # - gocyclo
  # - lll
  # - goconst
  # - errcheck
  # - dupl
