blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://dexidp.io/docs/
    about: Check the documentation for help

  - name: 💬 Slack channel
    url: https://kubernetes.slack.com/messages/dexidp
    about: Please ask and answer questions here
