issuer: http://127.0.0.1:5556
storage:
  type: sqlite3
  config:
    file: examples/dex.db

web:
  http: 127.0.0.1:5556

connectors:
- type: mockCallback
  id: mock-callback
  name: Mock
- type: mockPassword
  id: mock-password
  name: Password
  config:
    username: "admin"
    password: "PASSWORD"

staticClients:
- id: example-app
  redirectURIs:
  - 'http://127.0.0.1:5555/callback'
  name: 'Example App'
  secret: ZXhhbXBsZS1hcHAtc2VjcmV0
